### PR TITLE
Update placement of stack-action from 'options' to 'cli'

### PR DESCRIPTION
**Pull request by PhillypHenning**
Small update to stack-action, removed from options and put into cli ....

Closes https://github.com/bitovi/bitops/issues/227
Closes https://github.com/bitops-plugins/terraform/issues/18

### CODE REVIEW

**Review by armab — COMMENTED** [review]
It will also need a README update

https://github.com/bitops-plugins/terraform#cli-and-options-configuration-of-terraform-bitopsschemayaml

and bitops.sh docs

**Comment by armab** [comment]
@PhillypHenning Once merged, will it be a breaking change for the users?
To keep in mind for the migration instructions.

**Comment by PhillypHenning** [comment]
Yes... it will have impact if people are using that configuration value, however, we need to standardize its placement across the plugins. 

So; The sooner the better for the change. 

The doc is being updated in tandem, but this isn't something I was actively working on, just noting.

**Comment by armab** [comment]
The PR looks good, we'll also need an official documentation update in the bitops.sh.
So ideally, if we could merge those changes in one go.

**Comment by PhillypHenning** [comment]
BitOps core doc updated https://github.com/bitovi/bitops/pull/363

**Review by armab — APPROVED** [review]

**Pull request merged**
